# networks:
#   bisce-network:
#     external: true

volumes:
  orderer0:
    external: true
  peer0:
    external: true

services:
  orderer:
    container_name: orderer0
    image: hyperledger/fabric-orderer:latest
    env_file:
      - ../.env/.env.orderer
    volumes:
        - ../orderers/orderer0/msp:/var/hyperledger/orderer/msp
        - ../orderers/orderer0/tls:/var/hyperledger/orderer/tls
        - orderer0:/var/hyperledger/production/orderer
    working_dir: /root
    command: orderer
    # ports:
    #   - 7050:7050
    #   - 7053:7053
    #   - 9443:9443
    expose:
        - 7050
        - 7053
        - 9443
    # networks:
    #   - bisce-network
    network_mode: "host"

  couchdb:
    container_name: couchdb0
    image: couchdb:3.3.2
    env_file:
      - ../.env/.env.couchdb
    # ports:
    #   - "5984:5984"
    expose:
        - 5984
    # networks:
    #   - bisce-network
    network_mode: "host"

  peer:
    container_name: peer0
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    env_file:
      - ../.env/.env.peer
    volumes:
        - ..:/etc/hyperledger
        - peer0:/var/hyperledger/production
        - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    # ports:
    #   - 7051:7051
    #   - 9444:9444
    expose:
        - 7051
        - 9444
    depends_on:
      - couchdb
    # networks:
    #   - bisce-network
    network_mode: "host"
